name: "Makefile build push deploy"
description: "Makefile build push deploy"

inputs:
  project_id:
    required: false
    description: "GCP project id"
    type: string

  gcr_host:
    required: false
    description: "GCP container registry host"
    type: string

  chartmuseum_host:
    required: false
    description: "ChartMuseum host"
    type: string

  chartmuseum_user:
    required: false
    description: "ChartMuseum user"
    type: string

  chartmuseum_pass:
    required: false
    description: "ChartMuseum password"
    type: string

  install:
    required: false
    description: "make install"
    default: false
    type: boolean

  config:
    required: false
    description: "make config"
    default: false
    type: boolean

  build:
    required: false
    description: "make build"
    default: false
    type: boolean

  package:
    required: false
    description: "make package"
    default: false
    type: boolean

  deploy:
    required: false
    description: "make deploy"
    default: false
    type: boolean

  rollback:
    required: false
    description: "make rollback"
    default: false
    type: boolean

  rollback_release:
    required: false
    description: "rollback release"
    type: string

  rollback_revision:
    required: false
    description: "rollback revision"
    type: string

  prune:
    required: false
    description: "make prune"
    default: false
    type: boolean

  prune_all:
    required: false
    description: "make prune-all"
    default: false
    type: boolean

  destroy:
    required: false
    description: "make destroy"
    default: false
    type: boolean

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  using_cdn:
    required: false
    description: "Setup cdn for static assets"
    default: false
    type: boolean

  cdn_keep_latest_version:
    required: false
    description: "CDN keep latest version length"
    default: "2"
    type: string

  setup_helmfiles:
    required: false
    description: "Setup helmfiles"
    default: true
    type: boolean


outputs:
  build-time:
    description: "Define build time"
    value: ${{ steps.build-app.outputs.duration }}

  cdn-upload-path:
    description: "Define cdn upload path"
    value: ${{ steps.cdn-upload.outputs.path }}

  cdn-delete-path:
    description: "Define cdn delete path"
    value: ${{ steps.cdn-delete.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Setup yq
      uses: frenck/action-setup-yq@v1.0.2
      with:
        version: v4.30.6

    - name: Setup Helm
      uses: azure/setup-helm@v2

    - name: Setup Helmfile
      if: "${{ inputs.setup_helmfiles == 'true' }}"
      uses: kitabisa/actions/setup-helmfile@master

    - name: Install dependencies
      if: "${{ inputs.install == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        make install

    - name: Generate config for build time
      if: "${{ inputs.config == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        CHARTMUSEUM_HOST: ${{ inputs.chartmuseum_host }}
        CHARTMUSEUM_USER: ${{ inputs.chartmuseum_user }}
        CHARTMUSEUM_PASS: ${{ inputs.chartmuseum_pass }}
        DOCKER_REPOSITORY: ${{ inputs.gcr_host }}/${{ inputs.project_id }}
      run: |-
        make config

    - name: Build application
      id: build-app
      if: "${{ inputs.build == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        start=$(date +%s)
        make build
        echo "duration=$(($(date +%s)-$start))" >> $GITHUB_OUTPUT

    - name: Build and push docker image
      if: "${{ inputs.package == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        DOCKER_REPOSITORY: ${{ inputs.gcr_host }}/${{ inputs.project_id }}
      run: |-
        make package

    - name: Deploy via helmfile
      if: "${{ inputs.deploy == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        CHARTMUSEUM_HOST: ${{ inputs.chartmuseum_host }}
        CHARTMUSEUM_USER: ${{ inputs.chartmuseum_user }}
        CHARTMUSEUM_PASS: ${{ inputs.chartmuseum_pass }}
        DOCKER_REPOSITORY: ${{ inputs.gcr_host }}/${{ inputs.project_id }}
      run: |-
        make deploy

    - name: Destroy via helmfile
      if: "${{ inputs.destroy == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        make destroy || true

    - name: Rollback deployment
      if: "${{ inputs.rollback == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        RELEASE: ${{ inputs.rollback_release }}
        REVISION: ${{ inputs.rollback_revision }}
      run: |-
        make rollback

    - name: Get Helm history
      if: "${{ inputs.prune == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      id: helm-history
      run: |-
        echo "length=$(make helm-history-length)" >> $GITHUB_OUTPUT

    - name: Get Helm revision
      if: "${{ inputs.prune == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      id: helm-revision
      run: |-
        echo "oldest=$(make helm-oldest-revision)" >> $GITHUB_OUTPUT

    - name: Get Helm values
      if: "${{ (inputs.prune == 'true') && (steps.helm-revision.outputs.oldest != 0) }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      id: helm-values
      env:
        REVISION: ${{ steps.helm-revision.outputs.oldest }}
      run: |-
        echo "image-tag=$(make helm-image-tag)" >> $GITHUB_OUTPUT

    - name: Get Image timestamp
      if: "${{ (inputs.prune == 'true') && (steps.helm-values.outputs.image-tag != '') }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      id: helm-timestamp
      env:
        DOCKER_REPOSITORY: ${{ inputs.gcr_host }}/${{ inputs.project_id }}
        REVISION_IMAGE: ${{ steps.helm-values.outputs.image-tag }}
      run: |-
        echo "image-timestamp=$(make helm-image-timestamp)" >> $GITHUB_OUTPUT

    - name: Remove unused Docker images
      if: "${{ (inputs.prune == 'true') && (steps.helm-timestamp.outputs.image-timestamp != '') }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        DOCKER_REPOSITORY: ${{ inputs.gcr_host }}/${{ inputs.project_id }}
        REVISION_TIMESTAMP: ${{ steps.helm-timestamp.outputs.image-timestamp }}
        IMAGE_TAG: ${{ steps.helm-values.outputs.image-tag }}
      run: |-
        make prune || true

    - name: Remove all unused Docker images
      if: "${{ inputs.prune_all == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        DOCKER_REPOSITORY: ${{ inputs.gcr_host }}/${{ inputs.project_id }}
      run: |-
        make prune-all || true

    - name: Get cdn upload path
      if: "${{ inputs.using_cdn == 'true' }}"
      id: cdn-upload
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        echo "path=$(make get-cdn-upload-path)" >> $GITHUB_OUTPUT

    - name: Get cdn delete path
      if: "${{ inputs.using_cdn == 'true' }}"
      id: cdn-delete
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        SKIP_VERSION: ${{ inputs.cdn_keep_latest_version }}
      run: |-
        echo "path=$(make get-cdn-delete-path)" >> $GITHUB_OUTPUT
