name: "Setup dependencies tools" # Install & preparation tools
description: "Setup dependencies tools"

inputs:
  setup_buildx:
    required: false
    description: "Setup buildx"

  setup_task:
     required: false
     description: "Setup task"

runs:
  using: "composite"
  steps:
    - name: Setup docker buildx
      if: "${{ inputs.setup_buildx == 'true' }}"
      uses: docker/setup-buildx-action@v3

    - name: Setup Taskfile
      if: "${{ inputs.setup_task == 'true' }}"
      uses: arduino/setup-task@v1.0.3
