name: "Setup dependencies tools" # Install & preparation tools
description: "Setup dependencies tools"

inputs:
  setup_buildx:
    required: false
    description: "Setup buildx"

runs:
  using: "composite"
  steps:
    - name: Setup docker buildx
      if: "${{ inputs.setup_buildx == 'true' }}"
      uses: docker/setup-buildx-action@v3
