name: "Setup pnpm"
description: "Setup pnpm & cache modules"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."

  using_nextjs:
    required: false
    description: "Setup next.js cache modules"
    default: false
    type: boolean

  pnpm_version:
    required: true
    description: "Setup pnpm version"
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: ${{ inputs.pnpm_version }}

    - name: Cache Next.js
      if: "${{ inputs.using_nextjs == 'true' }}"
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/${{ inputs.working_directory }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-


