name: "Setup pnpm"
description: "Setup pnpm & cache modules"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  using_nextjs:
    required: false
    description: "Setup next.js cache modules"
    default: false
    type: string

  pnpm_version:
    required: false
    description: "Setup pnpm version"
    default: "latest"
    type: string

  cache:
    required: false
    description: "Run action cache"
    default: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache pnpm modules
      if: "${{ inputs.cache == 'true' }}"
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm_version }}

    - name: Set cache path Next.js
      if: "${{ inputs.using_nextjs == 'true' }}"
      shell: bash
      id: path
      env:
        INPUT_DIRECTORY: ${{ inputs.working_directory }}
      run: |-
        prefix="."
        string=$INPUT_DIRECTORY
        cache_path=${string#"$prefix"}
        echo "cache-path=${{ github.workspace }}$cache_path/.next/cache" >> $GITHUB_OUTPUT

    - name: Cache Next.js
      if: "${{ (inputs.using_nextjs == 'true' && inputs.cache == 'true') }}"
      uses: actions/cache@v3
      with:
        path: ${{ steps.path.outputs.cache-path }}
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-


