name: "Setup pnpm"
description: "Setup pnpm & cache modules"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  pnpm_version:
    required: false
    description: "Setup pnpm version"
    default: "latest"
    type: string

  using_nextjs:
    required: false
    description: "Setup next.js cache modules"
    default: false
    type: string

  cache:
    required: false
    description: "Run action cache"
    default: true
    type: string

runs:
  using: "composite"
  steps:
    # - name: Setup pnpm
    #   if: "${{ inputs.pnpm_version != 'latest' }}"
    #   uses: pnpm/action-setup@v4
    #   with:
    #     version: ${{ inputs.pnpm_version }}
    #     dest: /runner/.pnpm-store

    - name: Cache pnpm modules
      if: "${{ inputs.cache == 'true' }}"
      uses: actions/cache@v4
      with:
        path: /runner/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Set cache path Next.js
      if: "${{ inputs.using_nextjs == 'true' }}"
      shell: bash
      id: path
      env:
        INPUT_DIRECTORY: ${{ inputs.working_directory }}
      run: |-
        prefix="."
        string=$INPUT_DIRECTORY
        cache_path=${string#"$prefix"}
        echo "cache-path=${{ github.workspace }}$cache_path/.next/cache" >> $GITHUB_OUTPUT

    - name: Cache Next.js
      if: "${{ (inputs.using_nextjs == 'true' && inputs.cache == 'true') }}"
      uses: actions/cache@v4
      with:
        path: |
          /runner/.pnpm-store
          ${{ github.workspace }}/node_modules
          ${{ steps.path.outputs.cache-path }}
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-
