name: "setup bun"
description: "setup bun & cache modules"

runs:
  using: "composite"
  steps:
    - name: install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
  
    - name: cache bun modules
      if: "${{ inputs.cache == 'true' }}"
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
