name: "setup bun"
description: "setup bun"

inputs:
  bun_version:
    required: false
    description: "bun version"
    default: "latest"
    type: string

runs:
  using: "composite"
  steps:
    - name: install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun_version }}
