name: "Destroy deployment"
description: "Destroy release deployment"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"
    type: string

  gcr_host:
    required: true
    description: "GCP container registry host"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  prune_all:
    required: false
    description: "make prune-all"
    default: false
    type: string

  using_cdn:
    required: false
    description: "Setup cdn for static assets"
    default: false
    type: string

  delete_oldest_cdn:
    required: false
    description: "Setup delete oldest cdn"
    default: true
    type: string

  cdn_aws_s3_bucket:
    required: false
    description: "CDN aws s3 bucket"
    default: ""
    type: string

  cdn_aws_access_key_id:
    required: false
    description: "CDN aws access key id"
    default: ""
    type: string

  cdn_aws_secret_access_key:
    required: false
    description: "CDN aws secret access key"
    default: ""
    type: string

  cdn_aws_region:
    required: false
    description: "CDN aws region"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup gcloud
      uses: kitabisa/composite-actions/packages/gcloud@main
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Setup gke credential
      uses: kitabisa/composite-actions/packages/gke-credential@main
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Destroy release
      id: destroy-release
      uses: kitabisa/composite-actions/packages/makefile@main
      with:
        working_directory: ${{ inputs.working_directory }}
        project_id: ${{ inputs.project_id }}
        gcr_host: ${{ inputs.gcr_host }}
        destroy: true
        prune_all: ${{ inputs.prune_all }}
        using_cdn: ${{ inputs.using_cdn }}

    - name: Delete CDN static
      if: "${{ inputs.using_cdn == 'true' && inputs.delete_oldest_cdn == 'true' }}"
      uses: kitabisa/composite-actions/packages/cdn@main
      with:
        working_directory: ${{ inputs.working_directory }}
        cdn_aws_s3_bucket: ${{ inputs.cdn_aws_s3_bucket }}
        cdn_aws_access_key_id: ${{ inputs.cdn_aws_access_key_id }}
        cdn_aws_secret_access_key: ${{ inputs.cdn_aws_secret_access_key }}
        cdn_aws_region: ${{ inputs.cdn_aws_region }}
        delete: ${{ steps.destroy-release.outputs.cdn-delete-path }}
