name: "Manage CDN static"
description: "Manage CDN static for upload or delete"

inputs:
  cdn_aws_s3_bucket:
    required: false
    description: "CDN aws s3 bucket"
    default: ""
    type: string

  cdn_aws_access_key_id:
    required: false
    description: "CDN aws access key id"
    default: ""
    type: string

  cdn_aws_secret_access_key:
    required: false
    description: "CDN aws secret access key"
    default: ""
    type: string

  cdn_aws_region:
    required: false
    description: "CDN aws region"
    default: ""
    type: string

  cdn_source_dir:
    required: false
    description: "CDN source dir"
    default: ""
    type: string

  upload:
    required: false
    description: "Run upload CDN"
    default: true
    type: boolean

  upload_path:
    required: false
    description: "Upload dir"
    default: ""
    type: string

  delete:
    required: false
    description: "Run delete CDN"
    default: false
    type: boolean

  delete_path:
    required: false
    description: "Delete dir"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Upload CDN static
      if: "${{ inputs.upload == 'true' }}"
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --cache-control max-age=86400
      env:
        AWS_S3_BUCKET: ${{ inputs.cdn_aws_s3_bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.cdn_aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.cdn_aws_secret_access_key }}
        AWS_REGION: ${{ inputs.cdn_aws_region }}
        SOURCE_DIR: ${{ inputs.cdn_source_dir }}
        DEST_DIR: ${{ inputs.upload_path }}

    - name: Delete CDN static
      if: "${{ inputs.delete == 'true' }}"
      uses: vitorsgomes/s3-rm-action@master
      with:
        args: --recursive
      env:
        AWS_S3_BUCKET: ${{ inputs.cdn_aws_s3_bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.cdn_aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.cdn_aws_secret_access_key }}
        AWS_REGION: ${{ inputs.cdn_aws_region }}
        PATH_TO_DELETE: ${{ inputs.delete_path }}
