name: "Manage CDN static"
description: "Manage CDN static for upload or delete"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  cdn_aws_s3_bucket:
    required: true
    description: "CDN aws s3 bucket"
    type: string

  cdn_aws_access_key_id:
    required: true
    description: "CDN aws access key id"
    type: string

  cdn_aws_secret_access_key:
    required: true
    description: "CDN aws secret access key"
    type: string

  cdn_aws_region:
    required: true
    description: "CDN aws region"
    type: string

  cdn_source_dir:
    required: false
    description: "CDN source dir"
    default: ""
    type: string

  upload:
    required: false
    description: "Upload dir"
    default: ""
    type: string

  delete:
    required: false
    description: "Delete dir"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Upload CDN static
      if: "${{ inputs.upload != '' }}"
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --cache-control max-age=2592000
      env:
        AWS_S3_BUCKET: ${{ inputs.cdn_aws_s3_bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.cdn_aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.cdn_aws_secret_access_key }}
        AWS_REGION: ${{ inputs.cdn_aws_region }}
        SOURCE_DIR: ${{ inputs.working_directory }}/${{ inputs.cdn_source_dir }}
        DEST_DIR: ${{ inputs.upload }}

    - name: Delete CDN static
      if: "${{ inputs.delete != '' }}"
      uses: vitorsgomes/s3-rm-action@master
      with:
        args: --recursive
      env:
        AWS_S3_BUCKET: ${{ inputs.cdn_aws_s3_bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.cdn_aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.cdn_aws_secret_access_key }}
        AWS_REGION: ${{ inputs.cdn_aws_region }}
        PATH_TO_DELETE: ${{ inputs.delete }}
