name: "Static web deployment"
description: "Static web composite deployment"

inputs:
  # Required
  artifact_registry_host:
    required: true
    description: "Artifact registry host"
    type: string

  artifact_registry_project_id:
    required: true
    description: "Artifact registry project id"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  gh_token:
    required: true
    description: "Github token"

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setuptools
      uses: kitabisa/composite-actions/infra/tools/setuptools@v2
      with:
        setup_gcloud: true
        setup_buildx: true
        setup_kubectl: true
        setup_helm: true
        setup_helmfile: true
        gh_token: ${{ inputs.gh_token }}

    - name: Setup Gcloud credential
      uses: kitabisa/composite-actions/infra/tools/gcloud@v2
      with:
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        credentials_json: ${{ inputs.credentials_json }}
        project_id: ${{ inputs.project_id }}

    - name: Cache docker buildx
      uses: kitabisa/composite-actions/infra/tools/buildx@v2

    - name: Auth GKE credential
      uses: kitabisa/composite-actions/infra/tools/gke-credential@v2
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Build and push image
      uses: kitabisa/composite-actions/infra/tools/makefile@v2
      with:
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        artifact_registry_project_id: ${{ inputs.artifact_registry_project_id }}
        project_id: ${{ inputs.project_id }}
        working_directory: ${{ inputs.working_directory }}
        package: true

    - name: Deploy
      uses: kitabisa/composite-actions/infra/tools/makefile@v2
      with:
        working_directory: ${{ inputs.working_directory }}
        project_id: ${{ inputs.project_id }}
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        deploy: true
