name: "Rancher ns mover"
description: "configure namespace location on rancher project"

inputs:
  rancher_host:
    required: true
    description: "Rancher host"
    type: string

  rancher_access_key:
    required: true
    description: "Rancher access key"
    type: string

  rancher_secret_key:
    required: true
    description: "Rancher secret key"
    type: string

  rancher_cluster_id:
    required: true
    description: "Rancher cluster id"
    type: string

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

runs:
  using: "composite"
  steps:
    - name: Get business unit & app name values
      id: app-meta
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        echo "app-name=$(make get-app-name)" >> $GITHUB_OUTPUT
        echo "business-unit=$(make get-business-unit)" >> $GITHUB_OUTPUT

    - name: Configure namespace-project mapping in rancher
      uses: kitabisa/actions/rancher-ns-mover@master
      with:
        rancher-host: ${{ inputs.rancher_host }}
        rancher-access-key: ${{ inputs.rancher_access_key }}
        rancher-secret-key: ${{ inputs.rancher_secret_key }}
        cluster-id: ${{ inputs.rancher_cluster_id }}
        project-name: ${{ steps.app-meta.outputs.business-unit }}
        namespace: ${{ steps.app-meta.outputs.app-name }}
