name: "Setup dependencies tools" # Install & preparation tools
description: "Setup dependencies tools"

inputs:
  gh_user:
    required: true
    description: "gh user"

  gh_token:
    required: true
    description: "gh token"

  setup_git:
    required: false
    description: "Setup git"
    default: 'true'

  setup_go:
    required: false
    description: "Setup Go"
    default: 'true'

  cache_dependency_path:
    required: false
    description: "go sum location"
    default: "go.sum"

  go_version:
    required: false
    description: "go version"
    default: "^1.13.1"

  custom_command_flag:
    required: false
    description: "custom command flag"
    default: "false"

  custom_command:
    required: false
    description: "custom command"
    default: "echo no command"

  hash_files:
    required: false
    description: "hashFiles location"
    default: "**"


runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.gh_token }}

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}
        cache-dependency-path: ${{ inputs.working_directory }}/${{ inputs.cache_dependency_path }}
        cache: false

    - name: Setup Cache
      id: go-cache-paths
      shell: bash
      run: |
        echo "$(go env GOCACHE)"
        echo "$(go env GOMODCACHE)"

    # Cache go build cache, used to speedup go test
    - name: Go Build Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}
        restore-keys: |
          ${{ runner.os }}-go-build-${{ hashFiles(inputs.hash_files) }}
          ${{ runner.os }}-go-build

    # Cache go mod cache, used to speedup builds
    - name: Go Mod Cache
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-build-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}
        restore-keys: |
          ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          ${{ runner.os }}-go-build

    - name: Configure Git for private modules
      if: "${{ inputs.setup_git == 'true' }}"
      env:
        USER: ${{ inputs.gh_user }}
        TOKEN: ${{ inputs.gh_token }}
      shell: bash
      run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"


    # # Cache go build cache, used to speedup go test
    # - name: Go Build Cache
    #   uses: actions/cache@v4
    #   with:
    #     path: /home/runner/.cache/go-build
    #     key: ${{ runner.os }}-go-build-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-build-

    # # Cache go mod cache, used to speedup builds
    # - name: Go Mod Cache
    #   uses: actions/cache@v4
    #   with:
    #     path: /home/runner/go/pkg/mod
    #     key: ${{ runner.os }}-go-build-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-build-

    - name: Custom Command
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      if: "${{ inputs.custom_command_flag == 'true' }}"
      run: ${{ inputs.custom_command }}
