name: "Destroy deployment"
description: "Destroy release deployment"

inputs:
  # Required
  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  # Optional
  artifact_registry_host:
    required: false
    description: "Artifact registry host"
    type: string

  cdn_aws_s3_bucket:
    required: false
    description: "CDN aws s3 bucket"
    default: ""
    type: string

  cdn_aws_access_key_id:
    required: false
    description: "CDN aws access key id"
    default: ""
    type: string

  cdn_aws_secret_access_key:
    required: false
    description: "CDN aws secret access key"
    default: ""
    type: string

  cdn_aws_region:
    required: false
    description: "CDN aws region"
    default: ""
    type: string

  delete_oldest_cdn:
    required: false
    description: "Setup delete oldest cdn"
    default: true
    type: boolean

  prune_all:
    required: false
    description: "make prune-all"
    default: false
    type: boolean

  scheduler_destroy_dev:
    required: false
    description: "Scheduler for destroy dev"
    default: false
    type: boolean

  using_cdn:
    required: false
    description: "Setup cdn for static assets"
    default: false
    type: boolean

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string


runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Get GKE credential
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Install go
      uses: actions/setup-go@v4
      with:
        go-version: 1.17

    - name: Install task
      uses: arduino/setup-task@v1
      with:
        version: 3.x

    - name: Setup Helm
      uses: azure/setup-helm@v2

    - name: Destroy release
      id: destroy-release
      if: "${{ inputs.scheduler_destroy_dev == 'false' }}"
      uses: kitabisa/composite-actions/packages/makefile@v2
      with:
        working_directory: ${{ inputs.working_directory }}
        project_id: ${{ inputs.project_id }}
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        destroy: true
        prune_all: ${{ inputs.prune_all }}
        using_cdn: ${{ inputs.using_cdn }}

    - name: Delete CDN static
      if: "${{ inputs.using_cdn == 'true' && inputs.delete_oldest_cdn == 'true' }}"
      uses: kitabisa/composite-actions/packages/cdn@v2
      with:
        working_directory: ${{ inputs.working_directory }}
        cdn_aws_s3_bucket: ${{ inputs.cdn_aws_s3_bucket }}
        cdn_aws_access_key_id: ${{ inputs.cdn_aws_access_key_id }}
        cdn_aws_secret_access_key: ${{ inputs.cdn_aws_secret_access_key }}
        cdn_aws_region: ${{ inputs.cdn_aws_region }}
        delete: ${{ steps.destroy-release.outputs.cdn-delete-path }}

    - name: Copy taskfile
      shell: bash
      run: |-
        cp -r ${{ github.action_path }}/tasks/* .

    - name: Run destroy dev
      shell: bash
      run: |-
        task destroy-dev
