name: "Gcloud Auth"
description: "Gcloud authentication"

inputs:
  # Required
  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  # Optional
  artifact_registry_host:
    required: false
    description: "GCP artifact registry host for image container"
    type: string

  artifact_creds:
    required: false
    description: "Authentication gcloud"
    type: string
    default: 'true'

  docker_creds:
    required: false
    description: "Authentication gcloud"
    type: string
    default: 'true'

  gke_cluster_name:
    required: false
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: false
    description: "GKE cluster location zone"
    type: string

  gke_creds:
    required: false
    description: "Authentication gcloud"
    type: string
    default: 'true'

  gcloud_components:
    required: false
    description: "List of additional gcloud components to install"
    type: string

  service_account:
    required: false
    description: "Service Account name for workload identity"
    type: string

  workload_identity_provider:
    required: true
    description: "Workload identity provider"
    type: string

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ inputs.project_id }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: ${{ inputs.gcloud_components }}

    - name: Register gcloud as a docker credential helper
      if: "${{ inputs.docker_creds == 'true' }}"
      shell: bash
      run: |-
        gcloud auth configure-docker ${{ inputs.artifact_registry_host }} --project ${{ inputs.project_id }} --quiet

    - name: Register gcloud as a Artifact Registry credential helper
      if: "${{ inputs.artifact_creds == 'true' }}"
      shell: bash
      run: |-
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://asia-southeast1-docker.pkg.dev

    - name: Get GKE credential
      if: "${{ inputs.gke_creds == 'true' }}"
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}
