name: "Gcloud Auth"
description: "Gcloud authentication"

inputs:
  project_id:
    required: true
    description: "GCP project id"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  artifact_registry_host:
    required: false
    description: "GCP artifact registry host for image container"
    type: string

  auth_gcloud:
    required: false
    description: "Authentication gcloud"
    type: string
    default: 'true'

  docker_creds:
    required: false
    description: "Authentication gcloud"
    type: string
    default: 'true'

  artifact_creds:
    required: false
    description: "Authentication gcloud"
    type: string
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      if: "${{ inputs.auth_gcloud == 'true' }}"
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Register gcloud as a docker credential helper
      if: "${{ inputs.docker_creds == 'true' }}"
      shell: bash
      run: |-
        gcloud auth configure-docker ${{ inputs.artifact_registry_host }} --project ${{ inputs.project_id }} --quiet

    - name: Register gcloud as a Artifact Registry credential helper
      if: "${{ inputs.artifact_creds == 'true' }}"
      shell: bash
      run: |-
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{ inputs.artifact_registry_host }}
