name: "Gcloud Auth"
description: "Gcloud authentication"

inputs:
  project_id:
    required: true
    description: "GCP project id"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  artifact_registry_host:
    required: true
    description: "GCP artifact registry host for image container"
    type: string

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Register gcloud as a docker credential helper
      shell: bash
      run: |-
        gcloud auth configure-docker ${{ inputs.artifact_registry_host }} --project ${{ inputs.project_id }} --quiet

    - name: Register gcloud as a Artifact Registry credential helper
      shell: bash
      run: |-
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{ inputs.artifact_registry_host }}
