name: "Setup build & deploy packages"
description: "Setup docker, kubectl, helm & gcloud"

inputs:
  project_id:
    required: true
    description: "gcp project id"

  credentials_json:
    required: true
    description: "gcp credentials services account"

  gcr_host:
    required: true
    description: "gcp container registry host"

  gke_cluster_name:
    required: true
    description: "gke cluster name"

  gke_cluster_zone:
    required: true
    description: "gke cluster location zone"

runs:
  using: "composite"
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup Kubectl
      uses: azure/setup-kubectl@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0

    - name: Register gcloud as a Docker credential helper
      env:
        DOCKER_REGISTRY: ${{ inputs.gcr_host }}
        GCP_PROJECT_ID: ${{ inputs.project_id }}
      run: |-
        gcloud auth configure-docker "$DOCKER_REGISTRY" --project "$GCP_PROJECT_ID" --quiet

    - name: Get GKE credential
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Setup Helmfile
      uses: kitabisa/actions/setup-helmfile@master

    - name: Setup yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.11.2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-
