name: "manage env"
description: "manage environment variables for test automation"

inputs:
  profile:
    required: false
    description: "test profile"
    default: ""
    type: string

  slack_webhook_url:
    required: false
    description: "slack webhook url"
    default: ""
    type: string

  slack_webhook_debug_url:
    required: false
    description: "slack webhook debug url"
    default: ""
    type: string

  testrail_url:
    required: false
    description: "testrail url"
    default: ""
    type: string

  testrail_username:
    required: false
    description: "testrail username"
    default: ""
    type: string

  testrail_password:
    required: false
    description: "testrail password"
    default: ""
    type: string

  github_run_number:
    required: false
    description: "github run number"
    default: ""
    type: string

  credentials_sangu:
    required: false
    description: "credentials sangu"
    default: ""
    type: string

  password_sangu:
    required: false
    description: "password sangu"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: setup env variables
      shell: bash
      run: |
        make setup
        echo "TEST_TYPE=${{ inputs.profile }}" >> .env
        echo "SLACK_WEBHOOK_URL=${{ inputs.slack_webhook_url }}" >> .env
        echo "SLACK_WEBHOOK_DEBUG_URL=${{ inputs.slack_webhook_debug_url }}" >> .env
        echo "TESTRAIL_URL=${{ inputs.testrail_url }}" >> .env
        echo "TESTRAIL_USERNAME=${{ inputs.testrail_username }}" >> .env
        echo "TESTRAIL_PASSWORD=${{ inputs.testrail_password }}" >> .env
        echo "GITHUB_RUN_NUMBER=${{ inputs.github_run_number }}" >> .env
        echo "CREDENTIALS_SANGU=${{ inputs.credentials_sangu }}" >> .env
        echo "PASSWORD_SANGU=${{ inputs.password_sangu }}" >> .env
