name: "manage env"
description: "manage environment variables for test automation"

inputs:
  profile:
    required: true
    description: "test profile"
    type: string

runs:
  using: "composite"
  steps:
    - name: setup env variables
      shell: bash
      env:
        TEST_TYPE: ${{ inputs.profile }}
      run: |
        cp .env.sample .env
        echo "TEST_TYPE=Debug Test" >> .env
        echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_DEBUG_URL }}" >> .env
        echo "SLACK_WEBHOOK_DEBUG_URL=${{ secrets.SLACK_WEBHOOK_DEBUG_URL }}" >> .env
        echo "TESTRAIL_URL=${{ secrets.TESTRAIL_URL }}" >> .env
        echo "TESTRAIL_USERNAME=${{ secrets.TESTRAIL_USERNAME }}" >> .env
        echo "TESTRAIL_PASSWORD=${{ secrets.TESTRAIL_PASSWORD }}" >> .env
