name: "manage env"
description: "manage environment variables for test automation"

inputs:
  profile:
    required: false
    description: "test profile"
    default: ""
    type: string

  slack_webhook_url:
    required: false
    description: "slack webhook url"
    default: ""
    type: string

  slack_webhook_debug_url:
    required: false
    description: "slack webhook debug url"
    default: ""
    type: string

  testrail_url:
    required: false
    description: "testrail url"
    default: ""
    type: string

  testrail_username:
    required: false
    description: "testrail username"
    default: ""
    type: string

  testrail_password:
    required: false
    description: "testrail password"
    default: ""
    type: string

  github_run_number:
    required: false
    description: "github run number"
    default: ""
    type: string

  credentials_sangu:
    required: false
    description: "credentials sangu"
    default: ""
    type: string

  password_sangu:
    required: false
    description: "password sangu"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: setup env variables
      shell: bash
      run: |
        echo "TEST_TYPE=${{ inputs.profile }}" >> .env
        echo "GITHUB_RUN_NUMBER=${{ inputs.github_run_number }}" >> .env
