name: "manage env"
description: "manage environment variables for test automation"

inputs:
  profile:
    required: true
    description: "test profile"
    type: string

  slack_webhook_url:
    required: true
    description: "slack webhook url"
    type: string

  slack_webhook_debug_url:
    required: true
    description: "slack webhook debug url"
    type: string

  testrail_url:
    required: true
    description: "testrail url"
    type: string

  testrail_username:
    required: true
    description: "testrail username"
    type: string

  testrail_password:
    required: true
    description: "testrail password"
    type: string

runs:
  using: "composite"
  steps:
    - name: setup env variables
      shell: bash
      run: | 
        cp .env.sample .env
        echo "TEST_TYPE=${{ inputs.profile }}" >> $GITHUB_ENV
        echo "SLACK_WEBHOOK_URL=${{ inputs.slack_webhook_url }}" >> $GITHUB_ENV
        echo "SLACK_WEBHOOK_DEBUG_URL=${{ inputs.slack_webhook_debug_url }}" >> $GITHUB_ENV
        echo "TESTRAIL_URL=${{ inputs.testrail_url }}" >> $GITHUB_ENV
        echo "TESTRAIL_USERNAME=${{ inputs.testrail_username }}" >> $GITHUB_ENV
        echo "TESTRAIL_PASSWORD=${{ inputs.testrail_password }}" >> $GITHUB_ENV

    - name: check value env
      shell: bash
      run: |
        echo "$TEST_TYPE"
        echo "$SLACK_WEBHOOK_URL"
        echo "$SLACK_WEBHOOK_DEBUG_URL"
        echo "$TESTRAIL_URL"
        echo "$TESTRAIL_USERNAME"
        echo "$TESTRAIL_PASSWORD"
