name: "post pr actions"
description: "execute actions after pr is merged"

inputs:
  gh_token:
    required: true
    description: "gh token"
    default: "false"
    type: string

  setup_bun:
    required: false
    description: "setup bun"
    default: "false"
    type: string

  custom_command_packages:
    required: false
    description: "custom command packages"
    default: ""
    type: string

  custom_command_setup:
    required: true
    description: "custom command setup"
    default: ""
    type: string

  review_metrics_flag:
    description: "enable pr review metrics sync"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.gh_token }}

    - name: setup tools sdet
      uses: kitabisa/composite-actions/sdet/tools/setup-tools@v2
      with:
        setup_pnpm: ${{ inputs.setup_pnpm }}
        setup_bun: ${{ inputs.setup_bun }}
        setup_gh_cli: ${{ inputs.setup_gh_cli }}

    - name: install packages
      shell: bash
      run: ${{ inputs.custom_command_packages }}

    - name: setup env variables
      shell: bash
      run: |
        echo "environment setup complete with secret key."
        ${{ inputs.custom_command_setup }}

    - name: sync pr review metrics
      if: ${{ inputs.review_metrics_flag == 'true' && always() }}
      shell: bash
      run: |
        echo "Loading KRESEK credentials from dotenv..."
        eval $(bunx dotenvx run -f .env -- printenv | grep KRESEK)

        OWNER="${{ github.repository_owner }}"
        REPO="${{ github.event.repository.name }}"
        PR_NUMBER="${{ github.event.pull_request.number || env.PR_NUMBER_DISPATCH }}"

        if [ "$DRY_RUN" = "true" ]; then
          echo "🔍 [DRY RUN] Would execute API call:"
          echo "📡 Endpoint: $KRESEK_URL/pr/sync"
          echo "📦 Payload:"
          echo "{
            \"repository_owner\": \"${OWNER}\",
            \"repository_name\": \"${REPO}\",
            \"pr_number\": ${PR_NUMBER}
          }"
          echo "✅ [DRY RUN] API call simulation completed"
        else
          echo "🚀 Syncing metrics for PR #${PR_NUMBER} in ${OWNER}/${REPO}"

          curl -k -X POST \
            -u "$KRESEK_BASIC_AUTH_USERNAME:$KRESEK_BASIC_AUTH_PASSWORD" \
            -H "Content-Type: application/json" \
            -d "{
              \"repository_owner\": \"${OWNER}\",
              \"repository_name\": \"${REPO}\",
              \"pr_number\": ${PR_NUMBER}
            }" \
            "$KRESEK_URL/pr/sync"

          echo "✅ Metrics synced successfully"
        fi
