name: "Setup build & deploy packages"
description: "Setup docker, kubectl, helm & gcloud"

inputs:
  project_id:
    required: true
    description: "gcp project id"

  gcr_host:
    required: true
    description: "gcp container registry host"

runs:
  using: "composite"
  steps:
    - name: Get Helm history
      id: helm-history
      run: |-
        echo "::set-output name=length::$(make helm-history-length)"

    - name: Get Helm revision
      if: steps.helm-history.outputs.length >= 10
      id: helm-revision
      run: |-
        echo "::set-output name=oldest::$(make helm-oldest-revision)"

    - name: Get Helm values
      if: steps.helm-revision.outputs.oldest != 0
      id: helm-values
      env:
        REVISION: ${{ steps.helm-revision.outputs.oldest }}
      run: |-
        echo "::set-output name=image-tag::$(make helm-image-tag)"

    - name: Remove unused Docker images
      if: steps.helm-values.outputs.image-tag != 0
      env:
        DOCKER_REPOSITORY: ${{ inputs.gcr_host }}/${{ inputs.project_id }}
        IMAGE_TAG: ${{ steps.helm-values.outputs.image-tag }}
      run: |-
        make prune || true
