name: "Testing versioning composite"
description: "Testing versioning composite"

inputs:
  name:
    required: true
    description: "name"
    type: string

  company:
    required: true
    description: "company"
    type: string

  site:
    required: true
    description: "site"
    type: string

  location:
    required: true
    description: "site"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Build application
      shell: bash
      run: echo ${{ inputs.name }}

    - name: Build application
      shell: bash
      run: echo ${{ inputs.company }}

    - name: Build application
      shell: bash
      run: echo ${{ inputs.site }}

    - name: Build application
      shell: bash
      run: echo ${{ inputs.location }}
