name: "Setup Swagger Build"
description: "Setup Swagger build"

inputs:
  # Required
  artifact_registry_host:
    required: true
    description: "Artifact registry host"
    type: string

  artifact_registry_project_id:
    required: true
    description: "Artifact registry project id"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  # Optional
  swagger_script_path:
    required: false
    description: "shell script path and name for swagger env"

  setup_go:
    required: false
    description: "Setup Go"

  openapi_input_file:
    required: false
    description: "openapi input file"

  openapi_output_file:
    required: false
    description: "openapi output file"

runs:
  using: "composite"
  steps:
    - name: Replace env swagger
      shell: bash
      run: |-
        cd ${{ inputs.swagger_script_path }}
        sh swagger_env.sh

    - name: Setuptools backend
      uses: kitabisa/composite-actions/backend/tools/setuptools@refactor-composite
      with:
        setup_go: true

    # then use redoc-cli-github-action to generate your HTML bundle
    - name: install redoc
      shell: bash
      run: |-
        npm i -g @redocly/cli@latest

    - name: bundle openapi
      shell: bash
      run: |-
        openapi bundle ${{ inputs.openapi_input_file }} -o ${{ inputs.openapi_output_file }}
        cat ${{ inputs.openapi_output_file }}

    - name: Build, tag, and push Docker image Swagger
      shell: bash
      env:
        DOCKER_REPOSITORY: ${{ inputs.artifact_registry_host }}/${{ inputs.project_id }}/images
      run: |-
        make package-swagger
