name: "Taskfile"
description: "Taskfile cetralized command executor"

inputs:
  args:
    required: false
    description: "install"
    type: string

runs:
  using: "composite"
  steps:
    - name: Copy taskfile
      shell: bash
      run: |-
        cp -r ${{ github.action_path }}/tasks/* .

    - name: CI task for frontend
      shell: bash
      run: |-
        ${{ inputs.args }}

