name: "Taskfile"
description: "Taskfile cetralized command executor"

inputs:
  app_name:
    required: true
    description: "Application name"
    type: string

  artifact_registry_host:
    required: true
    description: "Artifact registry host"
    type: string

  business:
    required: true
    description: "business name"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  squad:
    required: true
    description: "Squad name"
    type: string

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

runs:
  using: "composite"
  steps:
    - name: Install go
      uses: actions/setup-go@v4
      with:
        go-version: 1.17

    - name: Install task
      uses: arduino/setup-task@v1
      with:
        version: 3.x

    - name: Setup yq
      uses: frenck/action-setup-yq@v1.0.2
      with:
        version: v4.30.6

    - name: Setup Helm
      uses: azure/setup-helm@v2

    - name: Register gcloud as a Artifact Registry credential helper
      shell: bash
      run: |-
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{ inputs.artifact_registry_host }}

    - name: Setup Helmfile
      uses: kitabisa/actions/setup-helmfile@master
      with:
        version: v0.144.0

    - name: CI task for frontend
      if: "${{ inputs.squad == 'frontend' }}"
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        APP_NAME: ${{ inputs.app_name }}
        SQUAD: ${{ inputs.squad }}
        BUSINESS: ${{ inputs.business }}
        DOCKER_REPOSITORY: ${{ inputs.artifact_registry_host }}/${{ inputs.project_id }}/images
      run: |-
        task frontend:install
        task frontend:config
        task frontend:build
        task frontend:package
