name: "Test Coverage"
description: "Build and push docker image"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  gh_user:
    required: true
    description: "gh user"

  gh_token:
    required: true
    description: "gh token"

  go_version:
    required: false
    description: "go version"
    default: "1.18"

  custom_command_flag:
    required: false
    description: "custom command flag"
    default: "false"

  custom_command:
    required: false
    description: "custom command"
    default: "echo no command"

  unit_test_command:
    required: false
    description: "unit test command"
    default: "go test ./internal/... -coverprofile=coverage.out -covermode=atomic"

  hash_files:
    required: false
    description: "hash files"
    default: "**"

  setup_restore_cache:
    required: false
    description: "setup cache"
    default: true

  setup_save_cache:
    required: false
    description: "setup cache"
    default: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.gh_token }}

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}
        cache: false

    - name: Start caching go
      shell: bash
      run: |
        echo "Start retrieving cache"

    - name: Restore Cache mod
      id: cache-restore-mod
      if: ${{ inputs.setup_restore_cache == 'true' }}
      uses: actions/cache/restore@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}

    - name: Restore Cache build
      id: cache-restore-build
      if: ${{ inputs.setup_restore_cache == 'true' }}
      uses: actions/cache/restore@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}

    - name: End caching go
      shell: bash
      run: |
        echo "End retrieving cache"

    - name: Configure Git for private modules
      env:
        USER: ${{ inputs.gh_user }}
        TOKEN: ${{ inputs.gh_token }}
      shell: bash
      run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Set base value
      shell: bash
      run: |
        echo "current_coverage=0" >> $GITHUB_ENV
        echo "master_coverage=0" >> $GITHUB_ENV

    - name: Generate Master Coverage
      id: unit-test-master
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        echo "master_coverage=$(cat coverage-master.txt)" >> $GITHUB_ENV

    - name: Custom Command
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      if: "${{ inputs.custom_command_flag == 'true' }}"
      run: ${{ inputs.custom_command }}

    - name: Run Unit tests
      id: unit-test-current
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        ${{ inputs.unit_test_command }}
        echo "current_coverage=$(go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')" >> $GITHUB_ENV

    - name: Comment PR and Set Fail Result
      if: fromJSON(env.current_coverage) < fromJSON(env.master_coverage)
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        message: |
          ##  ⚠⚠️ Unit Test Coverage ⚠⚠
          ```
          Current branch coverage : ${{ env.current_coverage }}
          Master branch coverage : ${{ env.master_coverage }}
          Condition: Current branch coverage must be bigger or equal than master branch coverage.
          ```
          <b> PR Blocked ❌. Please fix your unit test coverage </b>

    - name: Coverage below master, Fail PR
      if: fromJSON(env.current_coverage) < fromJSON(env.master_coverage)
      shell: bash
      run: |
        echo "::error :: unit test coverage is below master"
        exit 1

    - name: Comment PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        message: |
          ##  ✅✅ Unit Test Coverage ✅✅
          ```
          Current branch coverage : ${{ env.current_coverage }}
          Master branch coverage : ${{ env.master_coverage }}
          Condition: Current branch coverage must be bigger or equal than master branch coverage.
          ```
          PR Coverage check passed.

    - name: Install the gh cli
      if: ${{ inputs.setup_save_cache == 'true' }}
      uses: ksivamuthu/actions-setup-gh-cli@v2
      with:
        version: 2.24.3

    - name: Delete Previous Cache Mod
      if: ${{ steps.cache-restore-mod.outputs.cache-hit || inputs.setup_save_cache == 'true' }}
      continue-on-error: true
      shell: bash
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "${{ runner.os }}-go-mod-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}" --confirm
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - name: Save Cache Mod
      if: ${{ inputs.setup_save_cache == 'true' }}
      uses: actions/cache/save@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}

    - name: Delete Previous Cache Build
      if: ${{ steps.cache-restore-build.outputs.cache-hit || inputs.setup_save_cache == 'true' }}
      continue-on-error: true
      shell: bash
      run: |
        gh actions-cache delete "${{ runner.os }}-go-build-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}" --confirm
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - name: Save Cache Build
      if: ${{ inputs.setup_save_cache == 'true' }}
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build-${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}
