name: "Test Coverage"
description: "Build and push docker image"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  gh_user:
    required: true
    description: "gh user"

  gh_token:
    required: true
    description: "gh token"

  go_version:
    required: false
    description: "go version"
    default: "~1.22"

  custom_command_flag:
    required: false
    description: "custom command flag"
    default: "false"

  custom_command:
    required: false
    description: "custom command"
    default: "echo no command"

  unit_test_command:
    required: false
    description: "unit test command"
    default: "./internal/... -coverpkg=./internal/... -coverprofile=coverage.out -covermode=atomic"

  hash_files:
    required: false
    description: "hash files"
    default: "**"

  default_unit_test:
    required: false
    description: "default unit test"
    default: "true"

  setup_go_cache:
    required: false
    description: "go version"
    default: "false"

  setup_action_cache:
    required: false
    description: "setup cache"
    default: "true"

  cache_key_suffix:
    required: false
    description: Optional cache key suffix.
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.gh_token }}

    - name: Extract Go version
      id: go-version
      shell: bash
      run: |
        GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+' go.mod | awk '{print $2}')
        echo "Go version found: $GO_VERSION"
        echo "go_version=$GO_VERSION" >> $GITHUB_ENV

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        cache: ${{ inputs.setup_go_cache }}
        go-version: ${{ env.go_version }}

    # - name: Sleep debug only
    #   shell: bash
    #   run: sleep 120

    - name: Determine Golang cache paths and construct cache key
      id: golang-env
      run: |
        echo "build-cache-path=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
        echo "module-cache-path=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
        cacheKeyRoot="${{ runner.os }}-golang${{ inputs.cache_key_suffix && format('-{0}',inputs.cache_key_suffix) }}-"
        echo "cache-key-restore=$cacheKeyRoot" >>"$GITHUB_OUTPUT"
        echo "cache-key=${cacheKeyRoot}${{ hashFiles(format('{0}/{1}',inputs.hash_files,'go.sum')) }}" >>"$GITHUB_OUTPUT"
      shell: bash

    - name: Clean up Go cache
      shell: bash
      run: |
        sudo rm -rf ~/go/pkg/mod
        sudo rm -rf ~/.cache/go-build

    - name: Setup Golang cache
      if: ${{ inputs.setup_action_cache == 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ steps.golang-env.outputs.build-cache-path }}
          ${{ steps.golang-env.outputs.module-cache-path }}
        key: ${{ steps.golang-env.outputs.cache-key }}
        restore-keys: |
          ${{ steps.golang-env.outputs.cache-key-restore }}

    - name: Configure Git for private modules
      env:
        USER: ${{ inputs.gh_user }}
        TOKEN: ${{ inputs.gh_token }}
      shell: bash
      run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Custom Command
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      if: "${{ inputs.custom_command_flag == 'true' }}"
      run: |
        pwd
        ls -lah
        ${{ inputs.custom_command }}

    - name: Run Unit tests
      id: unit-test-current
      if: "${{ inputs.default_unit_test == 'true' }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        go test ${{ inputs.unit_test_command }}

    - name: Run Go Test Action
      if: "${{ inputs.default_unit_test == 'false' }}"
      uses: robherley/go-test-action@v0
      with:
        moduleDirectory: ${{ inputs.working_directory }}
        testArguments: ${{ inputs.unit_test_command }}
      continue-on-error: true

    - name: Annotate missing test coverage
      id: annotate
      if: github.event.pull_request.base.sha != ''
      shell: bash
      run: |
        git fetch origin master ${{ github.event.pull_request.base.sha }}
        curl -sLO https://github.com/vearutop/gocovdiff/releases/download/v1.3.4/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz && echo "b351c67526eefeb0671c82e9271ae984875865eed19e911f40f78348cb98347c  gocovdiff" | shasum -c
        REP=$(./gocovdiff -cov coverage.out -gha-annotations gha-unit.txt)
        echo "${REP}"
        REP="${REP//$'\n'/%0A}"
        cat gha-unit.txt
        echo "rep=$REP" >> "$GITHUB_OUTPUT"

    - name: Comment Test Coverage
      continue-on-error: true
      if: github.event.pull_request.base.sha != ''
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        header: unit-test
        message: |
          ### Unit Test Coverage
          <details><summary>Coverage of changed lines</summary>

          ${{ steps.annotate.outputs.rep }}
          </details>
