name: "Get GKE Credential"
description: "Get GKE Credential"

inputs:
  project_id:
    required: true
    description: "GCP project id"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"
    type: string

runs:
  using: "composite"
  steps:
    - name: Debug get-gke-creds
      shell: bash
      env:
        LOC: ${{ inputs.gke_cluster_zone }}
      run: |
        echo "GKE-ZONE: $LOC" | sed 's/./& /g'

    - name: Get GKE credential
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: asia-southeast1-a
        project_id: ${{ inputs.project_id }}
