version: '3'

silent: false

vars:
  NAMESPACE:
    sh: kubectl get ns | grep -v -e maxwell -e NAME -e slack-devbot-helper | awk '{ print $1 }'

tasks:
  destroy-dev:
    desc: Destroy dev
    cmds:
      - for: { var: NAMESPACE }
        cmd: helm ls -n {{.ITEM}} | grep "\-dev" | awk '{ print $1 }' | xargs -I % helm delete -n {{.ITEM}} % 2> /dev/null
        ignore_error: true
