name: "Rancher ns mover"
description: "configure namespace location on rancher project"

inputs:
  rancher_host:
    required: true
    description: "Rancher host"
    type: string

  rancher_access_key:
    required: true
    description: "Rancher access key"
    type: string

  rancher_secret_key:
    required: true
    description: "Rancher secret key"
    type: string

  rancher_cluster_id:
    required: true
    description: "Rancher cluster id"
    type: string

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  deploy:
    required: false
    description: "Run make deploy"
    default: "true"
    type: string

  deploy-kj:
    required: false
    description: "Run make deploy-kj"
    default: "false"
    type: string

  param:
    required: false
    description: "argument for service name"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Get business unit & app name values
      id: app-meta
      if: "${{ (inputs.deploy == 'true') && (inputs.deploy-kj == 'false') }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        echo "app-name=$(make get-app-name)" >> $GITHUB_OUTPUT

        if make -n get-platform >/dev/null 2>&1; then
          echo "platform=$(make get-platform)" >> $GITHUB_OUTPUT
        else
          echo "platform=$(make get-business-unit)" >> $GITHUB_OUTPUT
        fi

    - name: Get business unit & app name values
      id: app-meta-kj
      if: "${{ (inputs.deploy == 'false') && (inputs.deploy-kj == 'true') }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |-
        echo "app-name=$(make get-app-name)" >> $GITHUB_OUTPUT

        if make -n get-platform >/dev/null 2>&1; then
          echo "platform=$(make get-platform)" >> $GITHUB_OUTPUT
        else
          echo "platform=$(make get-business-unit)" >> $GITHUB_OUTPUT
        fi

    - name: Configure namespace-project mapping in rancher
      uses: kitabisa/actions/rancher-ns-mover@master
      if: "${{ (inputs.deploy == 'true') && (inputs.deploy-kj == 'false') }}"
      with:
        rancher-host: ${{ inputs.rancher_host }}
        rancher-access-key: ${{ inputs.rancher_access_key }}
        rancher-secret-key: ${{ inputs.rancher_secret_key }}
        cluster-id: ${{ inputs.rancher_cluster_id }}
        project-name: ${{ steps.app-meta.outputs.platform }}
        namespace: ${{ steps.app-meta.outputs.app-name }}

    - name: Configure namespace-project mapping in rancher project kitajaga
      uses: kitabisa/actions/rancher-ns-mover@master
      if: "${{ (inputs.deploy == 'false') && (inputs.deploy-kj == 'true') }}"
      with:
        rancher-host: ${{ inputs.rancher_host }}
        rancher-access-key: ${{ inputs.rancher_access_key }}
        rancher-secret-key: ${{ inputs.rancher_secret_key }}
        cluster-id: ${{ inputs.rancher_cluster_id }}
        project-name: ${{ steps.app-meta-kj.outputs.platform }}
        namespace: ${{ steps.app-meta-kj.outputs.app-name }}
