name: "automation test"
description: "build and run automation test"

inputs:
  gh_token:
    required: true
    description: "gh token"

  profile:
    required: false
    description: "profile"
    default: ""
    type: string

  platform:
    required: false
    description: "platform"
    default: ""
    type: string

  slack_webhook_url:
    required: false
    description: "slack webhook url"
    default: ""
    type: string

  slack_webhook_debug_url:
    required: false
    description: "slack webhook debug url"
    default: ""
    type: string

  testrail_url:
    required: false
    description: "testrail url"
    default: ""
    type: string

  testrail_username:
    required: false
    description: "testrail username"
    default: ""
    type: string

  testrail_password:
    required: false
    description: "testrail password"
    default: ""
    type: string

  setup_pnpm:
    required: false
    description: "setup pnpm"

  setup_bun:
    required: false
    description: "setup bun"

  github_run_number:
    required: false
    description: "github run number"
    default: ""
    type: string

  credentials_sangu:
    required: false
    description: "credentials sangu"
    default: ""
    type: string

  password_sangu:
    required: false
    description: "password sangu"
    default: ""
    type: string

  custom_command_packages:
    required: false
    description: "custom command packages"
    default: ""
    type: string

  custom_command_run:
    required: false
    description: "custom command run"
    default: ""
    type: string

  create_test_run:
    required: false
    description: "create test run"
    default: ""
    type: string

  setup_rsync:
    required: false
    description: "setup rsync"
    default: ""
    type: string

  custom_command_report_folder:
    required: false
    description: "custom command report folder"
    default: ""
    type: string

  insert_testrails:
    required: false
    description: "insert testrails"
    default: ""
    type: string

  custom_command_send_report_to_slack:
    required: false
    description: "custom command send report to slack"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.gh_token }}

    - name: setup tools sdet
      uses: kitabisa/composite-actions/sdet/tools/setup-tools@v2
      with:
        setup_pnpm: ${{ inputs.setup_pnpm }}
        setup_bun: ${{ inputs.setup_bun }}

    - name: install packages
      shell: bash
      run: ${{ inputs.custom_command_packages }}

    - name: setup env variables test automation
      uses: kitabisa/composite-actions/sdet/tools/env@v2
      with:
        profile: ${{ inputs.profile }}
        slack_webhook_url: ${{ inputs.slack_webhook_url }}
        slack_webhook_debug_url: ${{ inputs.slack_webhook_debug_url }}
        testrail_url: ${{ inputs.testrail_url }}
        testrail_username: ${{ inputs.testrail_username }}
        testrail_password: ${{ inputs.testrail_password }}
        github_run_number: ${{ inputs.github_run_number }}
        credentials_sangu: ${{ inputs.credentials_sangu }}
        password_sangu: ${{ inputs.password_sangu }}

    - name: create test run on testrails
      shell: bash
      if: "${{ inputs.create_test_run == 'true' && always() }}"
      run: bun run createTestrunTestrail

    - name: run automation test
      shell: bash
      if: always()
      run: ${{ inputs.custom_command_run }}

    - name: install rsync and bc
      shell: bash
      if: "${{ inputs.setup_rsync == 'true' && always() }}"
      run: sudo apt-get update && sudo apt-get install -y rsync && sudo apt-get install -y bc

    - name: deploy reports to github pages
      uses: kitabisa/composite-actions/sdet/deploy@v2
      if: always()
      with:
        custom_command_report_folder: ${{ inputs.custom_command_report_folder }}
        platform: ${{ inputs.platform }}
        profile: ${{ inputs.profile }}

    - name: insert result to testrails
      shell: bash
      if: "${{ inputs.insert_testrails == 'true' && always() }}"
      run: bun run insertResultTestrail

    - name: send report to slack
      shell: bash
      if: always()
      run: ${{ inputs.custom_command_send_report_to_slack }}
