name: "Setup yarn"
description: "Setup yarn & cache modules"

runs:
  using: "composite"
  steps:
    - name: Setup yarn
      run: npm install -g yarn

    - name: Cache yarn modules
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: yarn
        path: ~/.yarn-store
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache Next.js
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-


