name: "Setup yarn"
description: "Setup yarn & cache modules"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "${{ github.workspace }}"
    type: string

  using_nextjs:
    required: false
    description: "Setup next.js cache modules"
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Setup yarn
      shell: bash
      run: npm install -g yarn

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache Yarn packages
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache Next.js with working directory
      if: "${{ inputs.using_nextjs == 'true' }}"
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working_directory }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-


