name: "Setup Docker buildx"
description: "Setup Docker buildx credentials & cache"

inputs:
  artifact_registry_host:
    required: true
    description: "Artifact registry host"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  cache:
    required: false
    description: "Run action cache"
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Register gcloud as a docker credential helper
      shell: bash
      run: |-
        gcloud auth configure-docker ${{ inputs.artifact_registry_host }} --project ${{ inputs.project_id }} --quiet

    - name: Cache docker layers
      if: "${{ inputs.cache == 'true' }}"
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-
