name: "Setup Docker buildx"
description: "Setup Docker buildx credentials & cache"

inputs:
  artifact_registry:
    required: true
    description: "Artifact registry host"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  cache:
    required: false
    description: "Run action cache"
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Register gcloud as a docker credential helper
      shell: bash
      env:
        ARTIFACT_REGISTRY: ${{ inputs.artifact_registry }}
        GCP_PROJECT_ID: ${{ inputs.project_id }}
      run: |-
        gcloud auth configure-docker "$ARTIFACT_REGISTRY" --project "$GCP_PROJECT_ID" --quiet

    - name: Cache docker layers
      if: "${{ inputs.cache == 'true' }}"
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-
