name: "Helm charts build"
description: "Helm charts composite"

inputs:
  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  artifact_registry_host:
    required: true
    description: "GCP container registry host"
    type: string

  gh_token:
    required: true
    description: "gh token"

  path:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setuptools
      uses: kitabisa/composite-actions/infra/tools/setuptools@refactor-composite
      with:
        setup_gcloud: true
        setup_helm: true
        gh_token: ${{ inputs.token }}

    - name: Setup Gcloud credential
      uses: kitabisa/composite-actions/infra/tools/gcloud@refactor-composite
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Read Helm Chart
      id: chart
      uses: miraai/read-helm-chart-yaml@v0.1
      with:
        path: ${{ inputs.path }}/

    - name: Helm package
      shell: bash
      run: |-
        helm package ${{ inputs.path }}/

    - name: Push chart package to Artifact Registry
      shell: bash
      env:
        RELEASE_CHART: ${{ steps.chart.outputs.name }}-${{ steps.chart.outputs.version }}.tgz
      run: |-
        helm push "$RELEASE_CHART" oci://${{ inputs.artifact_registry_host }}/${{ inputs.project_id }}/charts
