name: "CI Build"
description: "Build and push docker image"

inputs:
  env:
    required: true
    description: "environment to deploy to"
    default: "dev"

  gh_token:
    required: true
    description: "gh token"

  project_id:
    required: true
    description: "GCP project id"

  gcr_host:
    required: true
    description: "GCP container registry host"

  chartmuseum_host:
    required: true
    description: "ChartMuseum host"

  chartmuseum_user:
    required: true
    description: "ChartMuseum user"

  chartmuseum_pass:
    required: true
    description: "ChartMuseum password"

  gke_cluster_name:
    required: true
    description: "GKE cluster name"

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"

  rancher_host:
    required: true
    description: "Rancher host"

  rancher_access_key:
    required: true
    description: "Rancher access key"

  rancher_secret_key:
    required: true
    description: "Rancher secret key"

  rancher_cluster_id:
    required: true
    description: "Rancher cluster id"


runs:
  using: "composite"
  steps:
    - name: Create prod deployment
      uses: chrnorm/deployment-action@v2
      id: deployment
      with:
        token: ${{ inputs.gh_token }}
        environment: ${{ inputs.env }}

    - name: Setup gke credential
      uses: kitabisa/composite-actions/packages/gke-credential@main
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Deploy
      uses: kitabisa/composite-actions/packages/makefile@main
      with:
        project_id: ${{ inputs.project_id }}
        gcr_host: ${{ inputs.gcr_host }}
        gh_token: ${{ inputs.gh_token }}
        chartmuseum_host: ${{ inputs.chartmuseum_host }}
        chartmuseum_user: ${{ inputs.chartmuseum_user }}
        chartmuseum_pass: ${{ inputs.chartmuseum_pass }}
        deploy: true

    - name: Rancher ns mover
      uses: kitabisa/composite-actions/packages/rancher@main
      with:
        working_directory: ${{ inputs.working_directory }}
        rancher_host: ${{ inputs.rancher_host }}
        rancher_access_key: ${{ inputs.rancher_access_key }}
        rancher_secret_key: ${{ inputs.rancher_secret_key }}
        rancher_cluster_id: ${{ inputs.rancher_cluster_id }}

    - uses: chrnorm/deployment-status@v2
      if: success()
      name: Set prod-test deployment success
      with:
        token: ${{ inputs.gh_token }}
        state: "success"
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}

    - uses: chrnorm/deployment-status@v2
      if: failure()
      name: Set prod-test deployment failure
      with:
        token: ${{ inputs.gh_token }}
        state: "failure"
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
