name: "CI Build"
description: "Build and push docker image"

inputs:
  env:
    required: true
    description: "environment to deploy to"
    default: "dev"

  gh_token:
    required: true
    description: "gh token"

  project_id:
    required: true
    description: "GCP project id"

  artifact_registry_host:
    required: true
    description: "Artifact registry host"

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"

  rancher_host:
    required: true
    description: "Rancher host"

  rancher_access_key:
    required: true
    description: "Rancher access key"

  rancher_secret_key:
    required: true
    description: "Rancher secret key"

  rancher_cluster_id:
    required: true
    description: "Rancher cluster id"

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  setup_helmfiles:
    required: false
    description: "Setup helmfiles"
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Create env deployment
      uses: chrnorm/deployment-action@v2
      id: deployment
      with:
        token: ${{ inputs.gh_token }}
        environment: ${{ inputs.env }}

    - name: Setup gcloud
      uses: kitabisa/composite-actions/packages/gcloud@v2
      with:
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Setup gke credential
      uses: kitabisa/composite-actions/packages/gke-credential@v2
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Deploy
      uses: kitabisa/composite-actions/packages/makefile@v2
      with:
        working_directory: ${{ inputs.working_directory }}
        project_id: ${{ inputs.project_id }}
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        deploy: true
        setup_helmfiles: ${{ inputs.setup_helmfiles }}

    - name: Rancher ns mover
      uses: kitabisa/composite-actions/packages/rancher@v2
      with:
        working_directory: ${{ inputs.working_directory }}
        rancher_host: ${{ inputs.rancher_host }}
        rancher_access_key: ${{ inputs.rancher_access_key }}
        rancher_secret_key: ${{ inputs.rancher_secret_key }}
        rancher_cluster_id: ${{ inputs.rancher_cluster_id }}

    - uses: chrnorm/deployment-status@v2
      if: success()
      name: Set env deployment success
      with:
        token: ${{ inputs.gh_token }}
        state: "success"
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}

    - uses: chrnorm/deployment-status@v2
      if: failure()
      name: Set env deployment failure
      with:
        token: ${{ inputs.gh_token }}
        state: "failure"
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
