name: "Setup yarn"
description: "Setup yarn & cache modules"

inputs:
  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  using_nextjs:
    required: false
    description: "Setup next.js cache modules"
    default: false
    type: string

  cache:
    required: false
    description: "Run action cache"
    default: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup yarn
      shell: bash
      run: npm install -g yarn

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: |-
        echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Cache Yarn packages
      if: "${{ inputs.cache == 'true' }}"
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Set cache path Next.js
      if: "${{ inputs.using_nextjs == 'true' }}"
      shell: bash
      id: path
      env:
        INPUT_DIRECTORY: ${{ inputs.working_directory }}
      run: |-
        prefix="."
        string=$INPUT_DIRECTORY
        cache_path=${string#"$prefix"}
        echo "cache-path=${{ github.workspace }}$cache_path/.next/cache" >> $GITHUB_OUTPUT

    - name: Cache Next.js
      if: "${{ (inputs.using_nextjs == 'true' && inputs.cache == 'true') }}"
      uses: actions/cache@v4
      with:
        path: ${{ steps.path.outputs.cache-path }}
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-


