name: "setup dependencies tools" # Install & preparation tools
description: "setup dependencies tools"

inputs:
  setup_pnpm:
    required: false
    description: "setup pnpm"
    default: "false"
    type: string

  setup_bun:
    required: false
    description: "setup bun"
    default: "false"
    type: string

  setup_gh_cli:
    required: false
    description: "setup gh cli"
    default: "false"
    type: string

runs:
  using: "composite"
  steps:
    - name: setup pnpm
      if: "${{ inputs.setup_pnpm == 'true' }}"
      uses: kitabisa/composite-actions/sdet/tools/pnpm@v2

    - name: setup bun
      if: "${{ inputs.setup_bun == 'true' }}"
      uses: kitabisa/composite-actions/sdet/tools/bun@v2

    - name: setup github cli
      if: "${{ inputs.setup_gh_cli == 'true' }}"
      uses: kitabisa/composite-actions/sdet/tools/gh_cli@v2
