version: '3'

env:
  VERSION: {sh: git describe --always --tags}
  GIT_COMMIT:  {sh: git rev-parse HEAD}
  GIT_DIRTY:  {sh: test -n "`git status --porcelain`" && echo "+CHANGES" || true}
  BUILD_DATE:  {sh: date '+%Y-%m-%d-%H:%M:%S'}

tasks:

  build:
    desc: Building apps
    vars:
      CI=true
      CI_ENV={{.ENV}}
      NODE_ENV=production
      VERSION={{.VERSION}}
    cmds:
      - echo '[*] Building apps {{.APP_NAME}} {{.VERSION}}'
      - go build -ldflags "-w -X github.com/kitabisa/sachie/version.GitCommit={{.GIT_COMMIT}}{{.GIT_DIRTY}} -X github.com/kitabisa/sachie/version.Version={{.VERSION}} -X github.com/kitabisa/sachie/version.Environment={{.ENV}} -X github.com/kitabisa/sachie/version.BuildDate={{.BUILD_DATE}}" -o bin/{{.APP_NAME}}

  package:
    desc: Build & push images
    cmds:
      - echo '[*] Build, tag, and push Docker image {{.APP_NAME}} {{.VERSION}}'
      - |
        docker buildx build \
          --build-arg VERSION={{.VERSION}} \
          --build-arg GIT_COMMIT={{.GIT_COMMIT}}{{.GIT_DIRTY}} \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache \
          --tag {{.DOCKER_REPOSITORY}}/{{.APP_NAME}}:{{.GIT_COMMIT}} \
          --tag {{.DOCKER_REPOSITORY}}/{{.APP_NAME}}:{{.VERSION}} \
          --tag {{.DOCKER_REPOSITORY}}/{{.APP_NAME}}:latest \
          --push .

  deploy:
    desc: Deploy apps
    cmds:
      - echo '[*] Deploying {{.APP_NAME}} {{.VERSION}}'
      - helmfile apply
