name: "Helmfiles"
description: "Deploy Releases"

inputs:
  gh_token:
    required: true
    description: "Github token"

  project_id:
    required: true
    description: "GCP project id"
    type: string

  artifact_registry_host:
    required: true
    description: "Artifact registry host"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setuptools
      uses: kitabisa/composite-actions/infra/tools/setuptools@v2
      with:
        setup_yq: true
        setup_gcloud: true
        setup_helm: true
        setup_helmfile: true
        credentials_json: ${{ inputs.credentials_json }}
        project_id: ${{ inputs.project_id }}

    - name: Setup Gcloud credential
      uses: kitabisa/composite-actions/infra/tools/gcloud@v2
      with:
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        project_id: ${{ inputs.project_id }}

    - name: Auth GKE credential
      uses: kitabisa/composite-actions/infra/tools/gke-credential@v2
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Deploy
      uses: kitabisa/composite-actions/infra/tools/makefile@v2
      with:
        project_id: ${{ inputs.project_id }}
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        deploy: true
