name: "CI Build"
description: "Build and push docker image"

inputs:
  # Required
  gh_token:
    required: true
    description: "Github token"

  artifact_registry_host:
    required: true
    description: "Artifact registry host"
    type: string

  artifact_registry_project_id:
    required: true
    description: "Artifact registry project id"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"
    type: string

  env:
    required: true
    description: "environment to deploy to"
    default: "dev"

  rancher_host:
    required: true
    description: "Rancher host"

  rancher_access_key:
    required: true
    description: "Rancher access key"

  rancher_secret_key:
    required: true
    description: "Rancher secret key"

  rancher_cluster_id:
    required: true
    description: "Rancher cluster id"

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  deploy_test:
    required: false
    description: "Run make deploy-test"
    default: "false"
    type: string

runs:
  using: "composite"
  steps:
    - name: Create env deployment
      uses: chrnorm/deployment-action@v2
      id: deployment
      with:
        token: ${{ inputs.gh_token }}
        environment: ${{ inputs.env }}

    - name: Checking out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ inputs.gh_token }}

    - name: Setuptools
      uses: kitabisa/composite-actions/infra/tools/setuptools@v2
      with:
        setup_kubectl: true
        setup_helm: true
        setup_helmfile: true

    - name: Setup Gcloud credential
      uses: kitabisa/composite-actions/infra/tools/gcloud@v2
      with:
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Auth GKE credential
      uses: kitabisa/composite-actions/infra/tools/gke-credential@v2
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Deploy
      uses: kitabisa/composite-actions/infra/tools/makefile@v2
      with:
        working_directory: ${{ inputs.working_directory }}
        project_id: ${{ inputs.project_id }}
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        artifact_registry_project_id: ${{ inputs.artifact_registry_project_id }}
        deploy_test: ${{ inputs.deploy_test }}

    # - name: Rancher ns mover
    #   uses: kitabisa/composite-actions/packages/rancher@main
    #   with:
    #     working_directory: ${{ inputs.working_directory }}
    #     rancher_host: ${{ inputs.rancher_host }}
    #     rancher_access_key: ${{ inputs.rancher_access_key }}
    #     rancher_secret_key: ${{ inputs.rancher_secret_key }}
    #     rancher_cluster_id: ${{ inputs.rancher_cluster_id }}

    - uses: chrnorm/deployment-status@v2
      if: success()
      name: Set env deployment success
      with:
        token: ${{ inputs.gh_token }}
        state: "success"
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}

    - uses: chrnorm/deployment-status@v2
      if: failure()
      name: Set env deployment failure
      with:
        token: ${{ inputs.gh_token }}
        state: "failure"
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
