name: "Setup dependencies tools" # Install & preparation tools
description: "Setup dependencies tools"

inputs:
  setup_yarn:
    required: false
    description: "Setup yarn"

  setup_pnpm:
    required: false
    description: "Setup pnpm"

  cache:
    required: false
    description: "Run action cache"
    default: true
    type: string

  using_nextjs:
    required: false
    description: "Setup next.js cache modules"
    default: false
    type: string

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup yarn
      if: "${{ inputs.setup_yarn == 'true' }}"
      uses: kitabisa/composite-actions/frontend/tools/yarn@v2
      with:
        cache: ${{ inputs.cache }}
        using_nextjs: ${{ inputs.using_nextjs }}
        working_directory: ${{ inputs.working_directory }}

    - name: Setup pnpm
      if: "${{ inputs.setup_pnpm == 'true' }}"
      uses: kitabisa/composite-actions/frontend/tools/pnpm@v2
      with:
        cache: ${{ inputs.cache }}
        using_nextjs: ${{ inputs.using_nextjs }}
        working_directory: ${{ inputs.working_directory }}
