# Noted:
# This action required requirements even if your module doesn't need requirement.yaml
# Please create requirement.yaml in your playbooks with value below.
# ---
# collections: []

name: "Ansible Playbook"
description: "Run Ansible Playbooks"

inputs:
  path:
    required: true
    description: "Ansible Playbook path"
    type: string

  ssh_private_key:
    required: true
    description: "SSH Private Key"
    type: string

  vault_password:
    required: false
    description: "Vault password"
    type: string

  workload_identity_provider:
    required: true
    description: "Workload identity pool"
    type: string

  service_account:
    required: true
    description: "SA used in workload identity pool"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: authenticate to google cloud with workload identity
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Decrypt secrets
      shell: bash
      run: |
        cd ${{ inputs.path }}
        cat secret.yaml
        mv secret.yaml secret.yaml.enc
        cat secret.yaml.enc
        sops -d secret.yaml.enc > secret.yaml

    - name: Provisioning Server
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yaml
        directory: ${{ inputs.path }}
        key: ${{ inputs.ssh_private_key }}
        requirements: requirements.yaml
        # vault_password: ${{ inputs.vault_password }}
