name: "trigger automation test when deploy completed"
description: "build and trigger automation test api when deploy completed"

inputs:
  gh_token:
    required: true
    description: "gh token"
    default: "false"
    type: string

  service_name:
    required: false
    description: "service name"
    default: "false"
    type: string

  trigger_automation_test_api_when_deploy:
    required: false
    description: "trigger automation test api when deploy"
    default: "false"
    type: string

  pr_author:
    required: false
    description: "author of the pull request"
    default: "unknown author"
    type: string

  pr_link:
    required: false
    description: "link to the pull request"
    default: "not available"
    type: string

runs:
  using: "composite"
  steps:
    - name: delay
      shell: bash
      if: "${{ inputs.trigger_automation_test_api_when_deploy == 'true' }}"
      run: sleep 10

    - name: trigger automation test api when deploy completed
      shell: bash
      if: "${{ inputs.trigger_automation_test_api_when_deploy == 'true' }}"
      run: |
        gh workflow run -R kitabisa/qorin .github/workflows/trigger-when-deploy.yaml \
          -f profile=${{ inputs.service_name }} \
          -f pr_author="${PR_AUTHOR}" \
          -f pr_link="${PR_LINK}" \
          --ref chore/sdet-1317-add-url-and-author-pr-to-slack-report
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
