name: "trigger automation test when deploy completed"
description: "setup and trigger automation test api when deploy completed"

inputs:
  gh_token:
    required: true
    description: "gh token"
    default: "false"
    type: string

  setup_pnpm:
    required: false
    description: "setup pnpm"
    default: "false"
    type: string

  setup_bun:
    required: false
    description: "setup bun"
    default: "false"
    type: string

  setup_gh_cli:
    required: false
    description: "setup gh cli"
    default: "false"
    type: string

  service_name:
    required: false
    description: "service name"
    default: "false"
    type: string

  trigger_automation_test_api_when_deploy:
    required: false
    description: "trigger automation test api when deploy"
    default: "false"
    type: string

  pr_author:
    required: false
    description: "author of the pull request"
    default: "unknown author"
    type: string

  pr_link:
    required: false
    description: "link to the pull request"
    default: "not available"
    type: string

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.gh_token }}

    - name: setup tools sdet
      uses: kitabisa/composite-actions/sdet/tools/setup-tools@v2
      with:
        setup_pnpm: ${{ inputs.setup_pnpm }}
        setup_bun: ${{ inputs.setup_bun }}
        setup_gh_cli: ${{ inputs.setup_gh_cli }}

    - name: get pr details
      shell: bash
      if: "${{ inputs.trigger_automation_test_api_when_deploy == 'true' }}"
      run: |
        PR_AUTHOR=$(gh pr list --state merged --base master --json author --jq '.[0].author.login')
        PR_LINK=$(gh pr list --state merged --base master --json url --jq '.[0].url')
        PR_BRANCH=$(gh pr list --state merged --base master --json headRefName --jq '.[0].headRefName')
        echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV
        echo "PR_LINK=$PR_LINK" >> $GITHUB_ENV
        echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}

    - name: delay
      shell: bash
      if: "${{ inputs.trigger_automation_test_api_when_deploy == 'true' }}"
      run: sleep 180

    - name: trigger automation test api when deploy completed
      shell: bash
      if: "${{ inputs.trigger_automation_test_api_when_deploy == 'true' }}"
      run: |
        if gh api repos/kitabisa/qorin/git/refs/heads/${PR_BRANCH} > /dev/null 2>&1; then
          TARGET_REF=${PR_BRANCH}
        else
          echo "branch ${PR_BRANCH} not found. Using fallback 'master'"
          TARGET_REF=master
        fi

        echo "Using ref: $TARGET_REF"

        gh workflow run -R kitabisa/qorin .github/workflows/trigger-when-deploy.yaml \
          -f profile=${{ inputs.service_name }} \
          -f pr_author="${PR_AUTHOR}" \
          -f pr_link="${PR_LINK}" \
          --ref "$TARGET_REF"
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
