name: "Helm charts build"
description: "Helm charts composite for ChartMuseum"

inputs:
  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  token:
    required: true
    description: "Github token"

  gke_cluster_name:
    required: true
    description: "GKE cluster name"

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"

  path:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setuptools
      uses: kitabisa/composite-actions/infra/tools/setuptools@refactor-composite
      with:
        setup_gcloud: true
        setup_kubectl: true
        setup_helm: true
        gh_token: ${{ inputs.token }}

    - name: Setup Gcloud credential
      uses: kitabisa/composite-actions/infra/tools/gcloud@refactor-composite
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Auth GKE credential
      uses: kitabisa/composite-actions/infra/tools/gke-credential@refactor-composite
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Lint chart
      shell: bash
      run: |-
        helm lint ${{ inputs.path }}

    - name: Simulate an install
      shell: bash
      run: |-
        helm install ${{ inputs.path }} ${{ inputs.path }}/. -f ${{ inputs.path }}/values-test.yaml -n test --dry-run
