name: "Helm charts build"
description: "Helm charts composite for ChartMuseum"

inputs:
  artifact_registry_host:
    required: true
    description: "GCP container registry host"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gh_token:
    required: true
    description: "Github token"

  gke_cluster_name:
    required: true
    description: "GKE cluster name"

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"

  path:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v4

    - name: Setup Gcloud credential
      uses: kitabisa/composite-actions/infra/tools/gcloud@v2
      with:
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        credentials_json: ${{ inputs.credentials_json }}
        project_id: ${{ inputs.project_id }}
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}

    - name: Lint chart
      shell: bash
      run: |-
        helm lint ${{ inputs.path }}

    - name: Simulate an install
      shell: bash
      run: |-
        helm install ${{ inputs.path }} ${{ inputs.path }}/. -f ${{ inputs.path }}/values-test.yaml -n test --dry-run
