version: '3'

silent: false

vars:
  FILE: release.txt
  CONTENT:
    sh: helm ls -A | grep "\-dev" | awk '{ print $1, $2 }' > {{.FILE}}
  RELEASE:
    sh: cat {{.FILE}} | awk '{ print $1 }'

tasks:
  destroy-dev:
    desc: Destroy dev
    cmds:
      - for: { var: RELEASE }
        task: purge
        vars:
          RELEASE_DEV: '{{.ITEM}}'
          RELEASE_NS:
            sh: cat {{.FILE}} | grep {{.ITEM}} | awk '{ print $2 }'
      # - defer: rm -rf {{.FILE}}

  purge:
    desc: Iterate helm release dev
    cmds:
      # - echo 'helm delete -n {{.RELEASE_NS}} {{.RELEASE_DEV}}'
      - helm delete -n {{.RELEASE_NS}} {{.RELEASE_DEV}}

