version: '3'

silent: false

vars:
  NAMESPACE:
    sh: kubectl get ns | grep -v -e maxwell -e NAME | awk '{ print $1 }'

tasks:
  destroy-dev:
    desc: Destroy dev
    cmds:
      - for: { var: NAMESPACE }
        cmd: helm ls -n {{.ITEM}} | grep "\-dev" | awk '{ print $1 }' | xargs helm delete -n {{.ITEM}}
        ignore_error: true
