name: "Rollback deployment"
description: "Rollback release deployment"

inputs:
  gh_token:
    required: true
    description: "Github token"

  artifact_registry_host:
    required: true
    description: "Artifact registry host"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"
    type: string

  project_id:
    required: true
    description: "GCP project id"
    type: string

  rollback_release:
    required: false
    description: "rollback release"
    type: string

  rollback_revision:
    required: false
    description: "rollback revision"
    type: string

  namespace:
    required: false
    description: "tools namespace"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setuptools
      uses: kitabisa/composite-actions/infra/tools/setuptools@refactor-composite
      with:
        setup_kubectl: true
        setup_helm: true
        setup_helmfile: true
        gh_token: ${{ inputs.gh_token }}

    - name: Setup Gcloud credential
      uses: kitabisa/composite-actions/infra/tools/gcloud@refactor-composite
      with:
        artifact_registry_host: ${{ inputs.artifact_registry_host }}
        credentials_json: ${{ inputs.credentials_json }}
        project_id: ${{ inputs.project_id }}

    - name: Auth GKE credential
      uses: kitabisa/composite-actions/infra/tools/gke-credential@refactor-composite
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Rollback release
      uses: kitabisa/composite-actions/infra/tools/makefile@refactor-composite
      with:
        rollback_release: ${{ inputs.rollback_release }}
        rollback_revision: ${{ inputs.rollback_revision }}
        namespace: ${{ inputs.namespace }}
        rollback: true
