name: "Sync root config"
description: "Sync app secrets/config to the root infrastructure repository"

inputs:
  gh_token:
    required: true
    description: "GitHub token with access to the root infra repository"
    type: string

runs:
  using: "composite"
  steps:
    - name: Sync config to infra repo
      env:
        ENV: ${{ env.ENV }}
        INFRA_REPO_URL: https://x-token:${{ inputs.gh_token }}@github.com/kitabisa/root.git
      shell: bash
      run: $GITHUB_ACTION_PATH/main.sh
