name: "Frontend build"
description: "Frontend composite deployment"

inputs:
  project_id:
    required: true
    description: "GCP project id"
    type: string

  credentials_json:
    required: true
    description: "GCP credentials services account"
    type: string

  gcr_host:
    required: true
    description: "GCP container registry host"
    type: string

  chartmuseum_host:
    required: true
    description: "ChartMuseum host"
    type: string

  chartmuseum_user:
    required: true
    description: "ChartMuseum user"
    type: string

  chartmuseum_pass:
    required: true
    description: "ChartMuseum password"
    type: string

  gke_cluster_name:
    required: true
    description: "GKE cluster name"
    type: string

  gke_cluster_zone:
    required: true
    description: "GKE cluster location zone"
    type: string

  rancher_host:
    required: true
    description: "Rancher host"
    type: string

  rancher_access_key:
    required: true
    description: "Rancher access key"
    type: string

  rancher_secret_key:
    required: true
    description: "Rancher secret key"
    type: string

  rancher_cluster_id:
    required: true
    description: "Rancher cluster id"
    type: string

  working_directory:
    required: false
    description: "Set working directory"
    default: "."
    type: string

  preview_url:
    required: false
    description: "Set preview url"
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup gcloud
      uses: kitabisa/composite-actions/packages/gcloud@main
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.credentials_json }}

    - name: Setup gke credential
      uses: kitabisa/composite-actions/packages/gke-credential@main
      with:
        gke_cluster_name: ${{ inputs.gke_cluster_name }}
        gke_cluster_zone: ${{ inputs.gke_cluster_zone }}
        project_id: ${{ inputs.project_id }}

    - name: Deploy & Prune
      uses: kitabisa/composite-actions/packages/makefile@main
      with:
        working_directory: ${{ inputs.working_directory }}
        project_id: ${{ inputs.project_id }}
        gcr_host: ${{ inputs.gcr_host }}
        chartmuseum_host: ${{ inputs.chartmuseum_host }}
        chartmuseum_user: ${{ inputs.chartmuseum_user }}
        chartmuseum_pass: ${{ inputs.chartmuseum_pass }}
        deploy: true
        prune: true

    - name: Rancher ns mover
      uses: kitabisa/composite-actions/packages/rancher@main
      with:
        working_directory: ${{ inputs.working_directory }}
        rancher_host: ${{ inputs.rancher_host }}
        rancher_access_key: ${{ inputs.rancher_access_key }}
        rancher_secret_key: ${{ inputs.rancher_secret_key }}
        rancher_cluster_id: ${{ inputs.rancher_cluster_id }}

    - name: Comment preview url
      if: "${{ inputs.preview_url != '' }}"
      uses: KeisukeYamashita/create-comment@v1
      with:
        comment: "Open the application by accessing these URL: [${{ inputs.preview_url }}](https://${{ inputs.preview_url }})"
