name: pre-commit check

on:
  pull_request:

env:
 BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cloudposse/github-action-pre-commit@v4.0.0
